# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicio.ui'
#
# Created: Wed Oct  9 08:55:18 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(880, 321)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet(_fromUtf8(""))
        self.btn_valida = QtGui.QPushButton(Form)
        self.btn_valida.setGeometry(QtCore.QRect(489, 20, 41, 24))
        self.btn_valida.setAutoFillBackground(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/buscar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_valida.setIcon(icon1)
        self.btn_valida.setFlat(True)
        self.btn_valida.setObjectName(_fromUtf8("btn_valida"))
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 461, 20))
        self.lineEdit.setAutoFillBackground(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(13, 115, 571, 16))
        self.line.setAutoFillBackground(True)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(50, 43, 361, 21))
        self.label_7.setAutoFillBackground(True)
        self.label_7.setStyleSheet(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lbl_desc = QtGui.QLabel(Form)
        self.lbl_desc.setGeometry(QtCore.QRect(40, 20, 441, 20))
        self.lbl_desc.setAutoFillBackground(True)
        self.lbl_desc.setObjectName(_fromUtf8("lbl_desc"))
        self.btn_folder = QtGui.QPushButton(Form)
        self.btn_folder.setGeometry(QtCore.QRect(540, 44, 41, 24))
        self.btn_folder.setAutoFillBackground(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/video.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_folder.setIcon(icon2)
        self.btn_folder.setFlat(True)
        self.btn_folder.setObjectName(_fromUtf8("btn_folder"))
        self.treeView = QtGui.QTreeView(Form)
        self.treeView.setGeometry(QtCore.QRect(593, 30, 281, 221))
        self.treeView.setAutoFillBackground(True)
        self.treeView.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeView.setSortingEnabled(True)
        self.treeView.setAnimated(True)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.lbl_perfil = QtGui.QLabel(Form)
        self.lbl_perfil.setGeometry(QtCore.QRect(593, 5, 231, 16))
        self.lbl_perfil.setAutoFillBackground(True)
        self.lbl_perfil.setObjectName(_fromUtf8("lbl_perfil"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(15, 124, 561, 161))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 24, 40, 16))
        self.label_2.setAutoFillBackground(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 42, 18, 16))
        self.label_3.setAutoFillBackground(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 64, 59, 16))
        self.label_4.setAutoFillBackground(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 46, 13))
        self.label_5.setAutoFillBackground(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 112, 46, 13))
        self.label_6.setAutoFillBackground(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lbl_autor = QtGui.QLabel(self.groupBox)
        self.lbl_autor.setGeometry(QtCore.QRect(70, 25, 411, 16))
        self.lbl_autor.setAutoFillBackground(True)
        self.lbl_autor.setObjectName(_fromUtf8("lbl_autor"))
        self.lbl_id = QtGui.QLabel(self.groupBox)
        self.lbl_id.setGeometry(QtCore.QRect(50, 43, 311, 16))
        self.lbl_id.setAutoFillBackground(True)
        self.lbl_id.setObjectName(_fromUtf8("lbl_id"))
        self.lbl_duracion = QtGui.QLabel(self.groupBox)
        self.lbl_duracion.setGeometry(QtCore.QRect(85, 64, 311, 16))
        self.lbl_duracion.setAutoFillBackground(True)
        self.lbl_duracion.setObjectName(_fromUtf8("lbl_duracion"))
        self.lbl_rating = QtGui.QLabel(self.groupBox)
        self.lbl_rating.setGeometry(QtCore.QRect(70, 89, 331, 16))
        self.lbl_rating.setAutoFillBackground(True)
        self.lbl_rating.setObjectName(_fromUtf8("lbl_rating"))
        self.lbl_visto = QtGui.QLabel(self.groupBox)
        self.lbl_visto.setGeometry(QtCore.QRect(60, 109, 341, 16))
        self.lbl_visto.setAutoFillBackground(True)
        self.lbl_visto.setObjectName(_fromUtf8("lbl_visto"))
        self.btn_valida_2 = QtGui.QPushButton(self.groupBox)
        self.btn_valida_2.setGeometry(QtCore.QRect(20, 130, 101, 27))
        self.btn_valida_2.setAutoFillBackground(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_valida_2.setIcon(icon3)
        self.btn_valida_2.setFlat(True)
        self.btn_valida_2.setObjectName(_fromUtf8("btn_valida_2"))
        self.lbl_imagen = QtGui.QLabel(self.groupBox)
        self.lbl_imagen.setGeometry(QtCore.QRect(360, 40, 161, 91))
        self.lbl_imagen.setAutoFillBackground(True)
        self.lbl_imagen.setStyleSheet(_fromUtf8(""))
        self.lbl_imagen.setScaledContents(True)
        self.lbl_imagen.setObjectName(_fromUtf8("lbl_imagen"))
        self.lbl_calidad = QtGui.QLabel(self.groupBox)
        self.lbl_calidad.setGeometry(QtCore.QRect(370, 130, 171, 30))
        self.lbl_calidad.setAutoFillBackground(True)
        self.lbl_calidad.setObjectName(_fromUtf8("lbl_calidad"))
        self.btn_folder_2 = QtGui.QPushButton(Form)
        self.btn_folder_2.setGeometry(QtCore.QRect(823, 4, 51, 24))
        self.btn_folder_2.setAutoFillBackground(True)
        self.btn_folder_2.setIcon(icon2)
        self.btn_folder_2.setFlat(True)
        self.btn_folder_2.setObjectName(_fromUtf8("btn_folder_2"))
        self.lst_encola = QtGui.QListWidget(Form)
        self.lst_encola.setGeometry(QtCore.QRect(590, 30, 281, 201))
        self.lst_encola.setAutoFillBackground(True)
        self.lst_encola.setFrameShape(QtGui.QFrame.NoFrame)
        self.lst_encola.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.lst_encola.setAlternatingRowColors(True)
        self.lst_encola.setObjectName(_fromUtf8("lst_encola"))
        self.btn_add = QtGui.QPushButton(Form)
        self.btn_add.setGeometry(QtCore.QRect(540, 20, 41, 24))
        self.btn_add.setAutoFillBackground(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/lista.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add.setIcon(icon4)
        self.btn_add.setFlat(True)
        self.btn_add.setObjectName(_fromUtf8("btn_add"))
        self.ck_captura = QtGui.QCheckBox(Form)
        self.ck_captura.setGeometry(QtCore.QRect(440, 83, 140, 20))
        self.ck_captura.setAutoFillBackground(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/clipboard.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ck_captura.setIcon(icon5)
        self.ck_captura.setObjectName(_fromUtf8("ck_captura"))
        self.ck_lst_auto = QtGui.QCheckBox(Form)
        self.ck_lst_auto.setGeometry(QtCore.QRect(440, 63, 137, 20))
        self.ck_lst_auto.setAutoFillBackground(True)
        self.ck_lst_auto.setIcon(icon4)
        self.ck_lst_auto.setObjectName(_fromUtf8("ck_lst_auto"))
        self.btn_add_video = QtGui.QPushButton(Form)
        self.btn_add_video.setGeometry(QtCore.QRect(595, 252, 118, 27))
        self.btn_add_video.setAutoFillBackground(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/add_video.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_video.setIcon(icon6)
        self.btn_add_video.setFlat(True)
        self.btn_add_video.setObjectName(_fromUtf8("btn_add_video"))
        self.btn_add_lista = QtGui.QPushButton(Form)
        self.btn_add_lista.setGeometry(QtCore.QRect(710, 252, 131, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_add_lista.setFont(font)
        self.btn_add_lista.setAutoFillBackground(True)
        self.btn_add_lista.setIcon(icon3)
        self.btn_add_lista.setFlat(True)
        self.btn_add_lista.setObjectName(_fromUtf8("btn_add_lista"))
        self.btn_paypal = QtGui.QPushButton(Form)
        self.btn_paypal.setGeometry(QtCore.QRect(520, 286, 51, 31))
        self.btn_paypal.setAutoFillBackground(True)
        self.btn_paypal.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/paypal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_paypal.setIcon(icon7)
        self.btn_paypal.setIconSize(QtCore.QSize(45, 45))
        self.btn_paypal.setFlat(True)
        self.btn_paypal.setObjectName(_fromUtf8("btn_paypal"))
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 70, 411, 31))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 61, 16))
        self.label.setAutoFillBackground(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.r_mp4 = QtGui.QRadioButton(self.groupBox_2)
        self.r_mp4.setGeometry(QtCore.QRect(90, 8, 77, 21))
        self.r_mp4.setAutoFillBackground(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/mp4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.r_mp4.setIcon(icon8)
        self.r_mp4.setChecked(True)
        self.r_mp4.setObjectName(_fromUtf8("r_mp4"))
        self.r_3gp = QtGui.QRadioButton(self.groupBox_2)
        self.r_3gp.setGeometry(QtCore.QRect(170, 8, 75, 21))
        self.r_3gp.setAutoFillBackground(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/3gp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.r_3gp.setIcon(icon9)
        self.r_3gp.setObjectName(_fromUtf8("r_3gp"))
        self.r_webm = QtGui.QRadioButton(self.groupBox_2)
        self.r_webm.setGeometry(QtCore.QRect(250, 8, 89, 21))
        self.r_webm.setAutoFillBackground(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/webm.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.r_webm.setIcon(icon10)
        self.r_webm.setObjectName(_fromUtf8("r_webm"))
        self.r_flv = QtGui.QRadioButton(self.groupBox_2)
        self.r_flv.setGeometry(QtCore.QRect(340, 8, 67, 21))
        self.r_flv.setAutoFillBackground(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/flv.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.r_flv.setIcon(icon11)
        self.r_flv.setObjectName(_fromUtf8("r_flv"))
        self.btn_de_item = QtGui.QPushButton(Form)
        self.btn_de_item.setGeometry(QtCore.QRect(743, 0, 124, 27))
        self.btn_de_item.setAutoFillBackground(True)
        self.btn_de_item.setIcon(icon3)
        self.btn_de_item.setFlat(True)
        self.btn_de_item.setObjectName(_fromUtf8("btn_de_item"))
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(575, 14, 20, 301))
        self.line_2.setAutoFillBackground(True)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.btn_facebook = QtGui.QPushButton(Form)
        self.btn_facebook.setGeometry(QtCore.QRect(80, 291, 38, 27))
        self.btn_facebook.setAutoFillBackground(True)
        self.btn_facebook.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/facebook.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_facebook.setIcon(icon12)
        self.btn_facebook.setIconSize(QtCore.QSize(16, 16))
        self.btn_facebook.setFlat(True)
        self.btn_facebook.setObjectName(_fromUtf8("btn_facebook"))
        self.btn_google = QtGui.QPushButton(Form)
        self.btn_google.setGeometry(QtCore.QRect(40, 291, 38, 27))
        self.btn_google.setAutoFillBackground(True)
        self.btn_google.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/googleplus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_google.setIcon(icon13)
        self.btn_google.setIconSize(QtCore.QSize(16, 16))
        self.btn_google.setFlat(True)
        self.btn_google.setObjectName(_fromUtf8("btn_google"))
        self.btn_twitter = QtGui.QPushButton(Form)
        self.btn_twitter.setGeometry(QtCore.QRect(4, 291, 38, 27))
        self.btn_twitter.setAutoFillBackground(True)
        self.btn_twitter.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/twitter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_twitter.setIcon(icon14)
        self.btn_twitter.setIconSize(QtCore.QSize(16, 16))
        self.btn_twitter.setFlat(True)
        self.btn_twitter.setObjectName(_fromUtf8("btn_twitter"))
        self.ck_vlc = QtGui.QCheckBox(Form)
        self.ck_vlc.setGeometry(QtCore.QRect(440, 100, 58, 20))
        self.ck_vlc.setAutoFillBackground(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/vlc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ck_vlc.setIcon(icon15)
        self.ck_vlc.setIconSize(QtCore.QSize(16, 16))
        self.ck_vlc.setObjectName(_fromUtf8("ck_vlc"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(2, 85, 35, 35))
        self.label_8.setBaseSize(QtCore.QSize(45, 45))
        self.label_8.setAutoFillBackground(True)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8("imagenes/python-3.png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.btn_valida.setToolTip(_translate("Form", "Buscar Video", None))
        self.btn_valida.setText(_translate("Form", "...", None))
        self.label_7.setText(_translate("Form", "Ejemplo: http://www.youtube.com/watch?v=QJO3ROT-A4E ", None))
        self.lbl_desc.setToolTip(_translate("Form", "Introduce la URL de Youtube", None))
        self.lbl_desc.setText(_translate("Form", "TextLabel", None))
        self.btn_folder.setToolTip(_translate("Form", "Motrar Videos", None))
        self.btn_folder.setText(_translate("Form", ">", None))
        self.treeView.setToolTip(_translate("Form", "Directorio Videos", None))
        self.lbl_perfil.setText(_translate("Form", "TextLabel", None))
        self.label_2.setText(_translate("Form", "Autor:", None))
        self.label_3.setText(_translate("Form", "ID:", None))
        self.label_4.setText(_translate("Form", "Duracion:", None))
        self.label_5.setText(_translate("Form", "Rating:", None))
        self.label_6.setText(_translate("Form", "Visto: ", None))
        self.lbl_autor.setText(_translate("Form", "Autor:", None))
        self.lbl_id.setText(_translate("Form", "ID:", None))
        self.lbl_duracion.setText(_translate("Form", "Duracion:", None))
        self.lbl_rating.setText(_translate("Form", "Rating:", None))
        self.lbl_visto.setText(_translate("Form", "Visto: ", None))
        self.btn_valida_2.setToolTip(_translate("Form", "Descarga el Video", None))
        self.btn_valida_2.setText(_translate("Form", "Descargar", None))
        self.lbl_imagen.setToolTip(_translate("Form", "Imagen Previa del Video", None))
        self.lbl_imagen.setText(_translate("Form", "https://i1.ytimg.com/vi/QJO3ROT-A4E/sddefault.jpg", None))
        self.lbl_calidad.setText(_translate("Form", "Calidad y Resolucion: ", None))
        self.btn_folder_2.setToolTip(_translate("Form", "<html><head/><body><p>Abrir Carpeta de Videos</p></body></html>", None))
        self.btn_folder_2.setText(_translate("Form", "...", None))
        self.lst_encola.setToolTip(_translate("Form", "Lista de Descarga", None))
        self.btn_add.setToolTip(_translate("Form", "Mostrar Lista", None))
        self.btn_add.setText(_translate("Form", ">", None))
        self.ck_captura.setToolTip(_translate("Form", "Capturar Enlaces de Youtube en Automatico", None))
        self.ck_captura.setText(_translate("Form", "Capturar Enlaces", None))
        self.ck_lst_auto.setToolTip(_translate("Form", "Lista Automatica", None))
        self.ck_lst_auto.setText(_translate("Form", "Lista Automatica", None))
        self.btn_add_video.setToolTip(_translate("Form", "Añadir Link a la Lista de Descargas", None))
        self.btn_add_video.setText(_translate("Form", "Añadir Video", None))
        self.btn_add_lista.setToolTip(_translate("Form", "Descargar Lista de videos", None))
        self.btn_add_lista.setText(_translate("Form", "Descargar Lista", None))
        self.btn_paypal.setToolTip(_translate("Form", "Donar en PayPal", None))
        self.label.setText(_translate("Form", "Formato:", None))
        self.r_mp4.setToolTip(_translate("Form", "Formato MP4", None))
        self.r_mp4.setText(_translate("Form", "mp4", None))
        self.r_3gp.setToolTip(_translate("Form", "Formato 3GP", None))
        self.r_3gp.setText(_translate("Form", "3gp", None))
        self.r_webm.setToolTip(_translate("Form", "Formato WEBM", None))
        self.r_webm.setText(_translate("Form", "webm", None))
        self.r_flv.setToolTip(_translate("Form", "Formato FLV", None))
        self.r_flv.setText(_translate("Form", "flv", None))
        self.btn_de_item.setToolTip(_translate("Form", "Eliminar Link", None))
        self.btn_de_item.setText(_translate("Form", "Eliminar Link", None))
        self.btn_facebook.setToolTip(_translate("Form", "Sigueme en Facebook", None))
        self.btn_google.setToolTip(_translate("Form", "Sigueme en G+", None))
        self.btn_twitter.setToolTip(_translate("Form", "Sigueme en Twitter", None))
        self.ck_vlc.setToolTip(_translate("Form", "Reproducir Videos en VLC", None))
        self.ck_vlc.setText(_translate("Form", "vlc", None))
        self.label_8.setToolTip(_translate("Form", "<html><head/><body><p>Programado en Python! y PyQt4 ..  xskyofx@gmail.com</p></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

