# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicio.ui'
#
# Created: Thu Oct  3 12:12:03 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(869, 288)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet(_fromUtf8(""))
        self.btn_valida = QtGui.QPushButton(Form)
        self.btn_valida.setGeometry(QtCore.QRect(489, 20, 41, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/buscar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_valida.setIcon(icon1)
        self.btn_valida.setFlat(True)
        self.btn_valida.setObjectName(_fromUtf8("btn_valida"))
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 461, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(13, 100, 551, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(14, 43, 551, 21))
        self.label_7.setStyleSheet(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lbl_desc = QtGui.QLabel(Form)
        self.lbl_desc.setGeometry(QtCore.QRect(40, 20, 441, 20))
        self.lbl_desc.setObjectName(_fromUtf8("lbl_desc"))
        self.btn_vlc = QtGui.QPushButton(Form)
        self.btn_vlc.setGeometry(QtCore.QRect(185, 40, 75, 24))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/eye.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_vlc.setIcon(icon2)
        self.btn_vlc.setFlat(True)
        self.btn_vlc.setObjectName(_fromUtf8("btn_vlc"))
        self.btn_otro = QtGui.QPushButton(Form)
        self.btn_otro.setGeometry(QtCore.QRect(261, 40, 131, 24))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_otro.setIcon(icon3)
        self.btn_otro.setFlat(True)
        self.btn_otro.setObjectName(_fromUtf8("btn_otro"))
        self.btn_folder = QtGui.QPushButton(Form)
        self.btn_folder.setGeometry(QtCore.QRect(530, 44, 41, 24))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/video.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_folder.setIcon(icon4)
        self.btn_folder.setFlat(True)
        self.btn_folder.setObjectName(_fromUtf8("btn_folder"))
        self.treeView = QtGui.QTreeView(Form)
        self.treeView.setGeometry(QtCore.QRect(575, 30, 281, 221))
        self.treeView.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeView.setSortingEnabled(True)
        self.treeView.setAnimated(True)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.lbl_perfil = QtGui.QLabel(Form)
        self.lbl_perfil.setGeometry(QtCore.QRect(580, 5, 211, 16))
        self.lbl_perfil.setObjectName(_fromUtf8("lbl_perfil"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(15, 116, 551, 161))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 46, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 62, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 83, 46, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 104, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lbl_autor = QtGui.QLabel(self.groupBox)
        self.lbl_autor.setGeometry(QtCore.QRect(60, 18, 481, 16))
        self.lbl_autor.setAutoFillBackground(False)
        self.lbl_autor.setObjectName(_fromUtf8("lbl_autor"))
        self.lbl_id = QtGui.QLabel(self.groupBox)
        self.lbl_id.setGeometry(QtCore.QRect(50, 38, 311, 16))
        self.lbl_id.setObjectName(_fromUtf8("lbl_id"))
        self.lbl_duracion = QtGui.QLabel(self.groupBox)
        self.lbl_duracion.setGeometry(QtCore.QRect(80, 60, 311, 16))
        self.lbl_duracion.setObjectName(_fromUtf8("lbl_duracion"))
        self.lbl_rating = QtGui.QLabel(self.groupBox)
        self.lbl_rating.setGeometry(QtCore.QRect(70, 80, 331, 16))
        self.lbl_rating.setObjectName(_fromUtf8("lbl_rating"))
        self.lbl_visto = QtGui.QLabel(self.groupBox)
        self.lbl_visto.setGeometry(QtCore.QRect(60, 101, 341, 16))
        self.lbl_visto.setObjectName(_fromUtf8("lbl_visto"))
        self.btn_valida_2 = QtGui.QPushButton(self.groupBox)
        self.btn_valida_2.setGeometry(QtCore.QRect(20, 130, 77, 24))
        self.btn_valida_2.setIcon(icon3)
        self.btn_valida_2.setFlat(True)
        self.btn_valida_2.setObjectName(_fromUtf8("btn_valida_2"))
        self.lbl_imagen = QtGui.QLabel(self.groupBox)
        self.lbl_imagen.setGeometry(QtCore.QRect(360, 40, 161, 91))
        self.lbl_imagen.setStyleSheet(_fromUtf8(""))
        self.lbl_imagen.setScaledContents(True)
        self.lbl_imagen.setObjectName(_fromUtf8("lbl_imagen"))
        self.lbl_calidad = QtGui.QLabel(self.groupBox)
        self.lbl_calidad.setGeometry(QtCore.QRect(417, 137, 171, 30))
        self.lbl_calidad.setObjectName(_fromUtf8("lbl_calidad"))
        self.btn_folder_2 = QtGui.QPushButton(Form)
        self.btn_folder_2.setGeometry(QtCore.QRect(800, 4, 51, 24))
        self.btn_folder_2.setIcon(icon4)
        self.btn_folder_2.setFlat(True)
        self.btn_folder_2.setObjectName(_fromUtf8("btn_folder_2"))
        self.lst_encola = QtGui.QListWidget(Form)
        self.lst_encola.setGeometry(QtCore.QRect(576, 30, 281, 201))
        self.lst_encola.setAutoFillBackground(True)
        self.lst_encola.setFrameShape(QtGui.QFrame.NoFrame)
        self.lst_encola.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.lst_encola.setAlternatingRowColors(True)
        self.lst_encola.setObjectName(_fromUtf8("lst_encola"))
        self.btn_add = QtGui.QPushButton(Form)
        self.btn_add.setGeometry(QtCore.QRect(530, 20, 41, 24))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/lista.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add.setIcon(icon5)
        self.btn_add.setFlat(True)
        self.btn_add.setObjectName(_fromUtf8("btn_add"))
        self.ck_captura = QtGui.QCheckBox(Form)
        self.ck_captura.setGeometry(QtCore.QRect(440, 84, 125, 20))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/clipboard.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ck_captura.setIcon(icon6)
        self.ck_captura.setObjectName(_fromUtf8("ck_captura"))
        self.ck_lst_auto = QtGui.QCheckBox(Form)
        self.ck_lst_auto.setGeometry(QtCore.QRect(440, 64, 122, 20))
        self.ck_lst_auto.setIcon(icon5)
        self.ck_lst_auto.setObjectName(_fromUtf8("ck_lst_auto"))
        self.btn_add_video = QtGui.QPushButton(Form)
        self.btn_add_video.setGeometry(QtCore.QRect(580, 252, 88, 24))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/add_video.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_video.setIcon(icon7)
        self.btn_add_video.setFlat(True)
        self.btn_add_video.setObjectName(_fromUtf8("btn_add_video"))
        self.btn_add_lista = QtGui.QPushButton(Form)
        self.btn_add_lista.setGeometry(QtCore.QRect(670, 252, 102, 24))
        self.btn_add_lista.setIcon(icon3)
        self.btn_add_lista.setFlat(True)
        self.btn_add_lista.setObjectName(_fromUtf8("btn_add_lista"))
        self.btn_paypal = QtGui.QPushButton(Form)
        self.btn_paypal.setGeometry(QtCore.QRect(817, 254, 51, 31))
        self.btn_paypal.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/paypal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_paypal.setIcon(icon8)
        self.btn_paypal.setIconSize(QtCore.QSize(45, 45))
        self.btn_paypal.setFlat(True)
        self.btn_paypal.setObjectName(_fromUtf8("btn_paypal"))
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 70, 411, 31))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 108, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.r_mp4 = QtGui.QRadioButton(self.groupBox_2)
        self.r_mp4.setGeometry(QtCore.QRect(130, 8, 63, 20))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/mp4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.r_mp4.setIcon(icon9)
        self.r_mp4.setChecked(True)
        self.r_mp4.setObjectName(_fromUtf8("r_mp4"))
        self.r_3gp = QtGui.QRadioButton(self.groupBox_2)
        self.r_3gp.setGeometry(QtCore.QRect(200, 8, 61, 20))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/3gp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.r_3gp.setIcon(icon10)
        self.r_3gp.setObjectName(_fromUtf8("r_3gp"))
        self.r_webm = QtGui.QRadioButton(self.groupBox_2)
        self.r_webm.setGeometry(QtCore.QRect(270, 8, 71, 20))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/webm.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.r_webm.setIcon(icon11)
        self.r_webm.setObjectName(_fromUtf8("r_webm"))
        self.r_flv = QtGui.QRadioButton(self.groupBox_2)
        self.r_flv.setGeometry(QtCore.QRect(350, 8, 55, 20))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/flv.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.r_flv.setIcon(icon12)
        self.r_flv.setObjectName(_fromUtf8("r_flv"))
        self.btn_de_item = QtGui.QPushButton(Form)
        self.btn_de_item.setGeometry(QtCore.QRect(770, 0, 85, 24))
        self.btn_de_item.setIcon(icon3)
        self.btn_de_item.setFlat(True)
        self.btn_de_item.setObjectName(_fromUtf8("btn_de_item"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.btn_valida.setToolTip(_translate("Form", "Buscar Video", None))
        self.btn_valida.setText(_translate("Form", "...", None))
        self.label_7.setText(_translate("Form", "Ejemplo: http://www.youtube.com/watch?v=QJO3ROT-A4E ", None))
        self.lbl_desc.setToolTip(_translate("Form", "Introduce la URL de Youtube", None))
        self.lbl_desc.setText(_translate("Form", "TextLabel", None))
        self.btn_vlc.setToolTip(_translate("Form", "Abre  Video en Reproductor VLC", None))
        self.btn_vlc.setText(_translate("Form", "Abrir VLC", None))
        self.btn_otro.setToolTip(_translate("Form", "Regresar al Formulario de busqueda", None))
        self.btn_otro.setText(_translate("Form", "Descargar Otro Video", None))
        self.btn_folder.setToolTip(_translate("Form", "Motrar Videos", None))
        self.btn_folder.setText(_translate("Form", ">", None))
        self.treeView.setToolTip(_translate("Form", "Directorio Videos", None))
        self.lbl_perfil.setText(_translate("Form", "TextLabel", None))
        self.label_2.setText(_translate("Form", "Autor:", None))
        self.label_3.setText(_translate("Form", "ID:", None))
        self.label_4.setText(_translate("Form", "Duracion:", None))
        self.label_5.setText(_translate("Form", "Rating:", None))
        self.label_6.setText(_translate("Form", "Visto: ", None))
        self.lbl_autor.setText(_translate("Form", "Autor:", None))
        self.lbl_id.setText(_translate("Form", "ID:", None))
        self.lbl_duracion.setText(_translate("Form", "Duracion:", None))
        self.lbl_rating.setText(_translate("Form", "Rating:", None))
        self.lbl_visto.setText(_translate("Form", "Visto: ", None))
        self.btn_valida_2.setToolTip(_translate("Form", "Descarga el Video en Mp4", None))
        self.btn_valida_2.setText(_translate("Form", "Descargar", None))
        self.lbl_imagen.setToolTip(_translate("Form", "Imagen Previa del Video", None))
        self.lbl_imagen.setText(_translate("Form", "https://i1.ytimg.com/vi/QJO3ROT-A4E/sddefault.jpg", None))
        self.lbl_calidad.setText(_translate("Form", "Calidad y Resolucion: ", None))
        self.btn_folder_2.setToolTip(_translate("Form", "<html><head/><body><p>Abrir Carpeta de Videos</p></body></html>", None))
        self.btn_folder_2.setText(_translate("Form", "...", None))
        self.lst_encola.setToolTip(_translate("Form", "Lista de Descarga", None))
        self.btn_add.setToolTip(_translate("Form", "Mostrar Lista", None))
        self.btn_add.setText(_translate("Form", ">", None))
        self.ck_captura.setToolTip(_translate("Form", "Capturar Enlaces de Youtube en Automatico", None))
        self.ck_captura.setText(_translate("Form", "Capturar Enlaces", None))
        self.ck_lst_auto.setToolTip(_translate("Form", "Lista Automatica", None))
        self.ck_lst_auto.setText(_translate("Form", "Lista Automatica", None))
        self.btn_add_video.setToolTip(_translate("Form", "Añadir Link a la Lista de Descargas", None))
        self.btn_add_video.setText(_translate("Form", "Añadir Video", None))
        self.btn_add_lista.setToolTip(_translate("Form", "Descargar Lista de videos", None))
        self.btn_add_lista.setText(_translate("Form", "Descargar Lista", None))
        self.btn_paypal.setToolTip(_translate("Form", "Donar en PayPal", None))
        self.label.setText(_translate("Form", "Selecciona el Formato:", None))
        self.r_mp4.setToolTip(_translate("Form", "Formato MP4", None))
        self.r_mp4.setText(_translate("Form", "mp4", None))
        self.r_3gp.setToolTip(_translate("Form", "Formato 3GP", None))
        self.r_3gp.setText(_translate("Form", "3gp", None))
        self.r_webm.setToolTip(_translate("Form", "Formato WEBM", None))
        self.r_webm.setText(_translate("Form", "webm", None))
        self.r_flv.setToolTip(_translate("Form", "Formato FLV", None))
        self.r_flv.setText(_translate("Form", "flv", None))
        self.btn_de_item.setToolTip(_translate("Form", "Eliminar Link", None))
        self.btn_de_item.setText(_translate("Form", "Eliminar Link", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

