# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicio.ui'
#
# Created: Fri Mar 14 23:48:34 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(880, 480)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet(_fromUtf8(""))
        self.btn_valida = QtGui.QPushButton(Form)
        self.btn_valida.setGeometry(QtCore.QRect(489, 20, 41, 24))
        self.btn_valida.setAutoFillBackground(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/buscar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_valida.setIcon(icon1)
        self.btn_valida.setFlat(True)
        self.btn_valida.setObjectName(_fromUtf8("btn_valida"))
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 461, 20))
        self.lineEdit.setAutoFillBackground(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(13, 115, 571, 16))
        self.line.setAutoFillBackground(True)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(50, 43, 361, 21))
        self.label_7.setAutoFillBackground(True)
        self.label_7.setStyleSheet(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lbl_desc = QtGui.QLabel(Form)
        self.lbl_desc.setGeometry(QtCore.QRect(40, 20, 441, 20))
        self.lbl_desc.setAutoFillBackground(True)
        self.lbl_desc.setObjectName(_fromUtf8("lbl_desc"))
        self.btn_folder = QtGui.QPushButton(Form)
        self.btn_folder.setGeometry(QtCore.QRect(540, 44, 41, 24))
        self.btn_folder.setAutoFillBackground(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/video.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_folder.setIcon(icon2)
        self.btn_folder.setFlat(True)
        self.btn_folder.setObjectName(_fromUtf8("btn_folder"))
        self.treeView = QtGui.QTreeView(Form)
        self.treeView.setGeometry(QtCore.QRect(593, 30, 281, 371))
        self.treeView.setAutoFillBackground(True)
        self.treeView.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeView.setSortingEnabled(True)
        self.treeView.setAnimated(True)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.lbl_perfil = QtGui.QLabel(Form)
        self.lbl_perfil.setGeometry(QtCore.QRect(593, 5, 231, 16))
        self.lbl_perfil.setAutoFillBackground(True)
        self.lbl_perfil.setObjectName(_fromUtf8("lbl_perfil"))
        self.btn_folder_2 = QtGui.QPushButton(Form)
        self.btn_folder_2.setGeometry(QtCore.QRect(823, 4, 51, 24))
        self.btn_folder_2.setAutoFillBackground(True)
        self.btn_folder_2.setIcon(icon2)
        self.btn_folder_2.setFlat(True)
        self.btn_folder_2.setObjectName(_fromUtf8("btn_folder_2"))
        self.lst_encola = QtGui.QListWidget(Form)
        self.lst_encola.setGeometry(QtCore.QRect(590, 30, 281, 361))
        self.lst_encola.setAutoFillBackground(True)
        self.lst_encola.setFrameShape(QtGui.QFrame.NoFrame)
        self.lst_encola.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.lst_encola.setAlternatingRowColors(True)
        self.lst_encola.setObjectName(_fromUtf8("lst_encola"))
        self.btn_add = QtGui.QPushButton(Form)
        self.btn_add.setGeometry(QtCore.QRect(540, 20, 41, 24))
        self.btn_add.setAutoFillBackground(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/lista.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add.setIcon(icon3)
        self.btn_add.setFlat(True)
        self.btn_add.setObjectName(_fromUtf8("btn_add"))
        self.ck_captura = QtGui.QCheckBox(Form)
        self.ck_captura.setGeometry(QtCore.QRect(440, 83, 140, 20))
        self.ck_captura.setAutoFillBackground(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/clipboard.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ck_captura.setIcon(icon4)
        self.ck_captura.setObjectName(_fromUtf8("ck_captura"))
        self.ck_lst_auto = QtGui.QCheckBox(Form)
        self.ck_lst_auto.setGeometry(QtCore.QRect(440, 63, 137, 20))
        self.ck_lst_auto.setAutoFillBackground(True)
        self.ck_lst_auto.setIcon(icon3)
        self.ck_lst_auto.setObjectName(_fromUtf8("ck_lst_auto"))
        self.btn_add_video = QtGui.QPushButton(Form)
        self.btn_add_video.setGeometry(QtCore.QRect(595, 410, 118, 27))
        self.btn_add_video.setAutoFillBackground(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/add_video.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_video.setIcon(icon5)
        self.btn_add_video.setFlat(True)
        self.btn_add_video.setObjectName(_fromUtf8("btn_add_video"))
        self.btn_add_lista = QtGui.QPushButton(Form)
        self.btn_add_lista.setGeometry(QtCore.QRect(710, 410, 131, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_add_lista.setFont(font)
        self.btn_add_lista.setAutoFillBackground(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_lista.setIcon(icon6)
        self.btn_add_lista.setFlat(True)
        self.btn_add_lista.setObjectName(_fromUtf8("btn_add_lista"))
        self.btn_paypal = QtGui.QPushButton(Form)
        self.btn_paypal.setGeometry(QtCore.QRect(520, 444, 51, 31))
        self.btn_paypal.setAutoFillBackground(True)
        self.btn_paypal.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/paypal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_paypal.setIcon(icon7)
        self.btn_paypal.setIconSize(QtCore.QSize(45, 45))
        self.btn_paypal.setFlat(True)
        self.btn_paypal.setObjectName(_fromUtf8("btn_paypal"))
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 70, 411, 31))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 61, 16))
        self.label.setAutoFillBackground(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.f_box = QtGui.QComboBox(self.groupBox_2)
        self.f_box.setGeometry(QtCore.QRect(97, 5, 91, 22))
        self.f_box.setAutoFillBackground(True)
        self.f_box.setObjectName(_fromUtf8("f_box"))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/mp4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.f_box.addItem(icon8, _fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/mp3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.f_box.addItem(icon9, _fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/3gp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.f_box.addItem(icon10, _fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/webm.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.f_box.addItem(icon11, _fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/flv.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.f_box.addItem(icon12, _fromUtf8(""))
        self.btn_de_item = QtGui.QPushButton(Form)
        self.btn_de_item.setGeometry(QtCore.QRect(743, 0, 124, 27))
        self.btn_de_item.setAutoFillBackground(True)
        self.btn_de_item.setIcon(icon6)
        self.btn_de_item.setFlat(True)
        self.btn_de_item.setObjectName(_fromUtf8("btn_de_item"))
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(575, 14, 20, 451))
        self.line_2.setAutoFillBackground(True)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.btn_facebook = QtGui.QPushButton(Form)
        self.btn_facebook.setGeometry(QtCore.QRect(80, 449, 38, 27))
        self.btn_facebook.setAutoFillBackground(True)
        self.btn_facebook.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/facebook.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_facebook.setIcon(icon13)
        self.btn_facebook.setIconSize(QtCore.QSize(16, 16))
        self.btn_facebook.setFlat(True)
        self.btn_facebook.setObjectName(_fromUtf8("btn_facebook"))
        self.btn_google = QtGui.QPushButton(Form)
        self.btn_google.setGeometry(QtCore.QRect(40, 449, 38, 27))
        self.btn_google.setAutoFillBackground(True)
        self.btn_google.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/googleplus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_google.setIcon(icon14)
        self.btn_google.setIconSize(QtCore.QSize(16, 16))
        self.btn_google.setFlat(True)
        self.btn_google.setObjectName(_fromUtf8("btn_google"))
        self.btn_twitter = QtGui.QPushButton(Form)
        self.btn_twitter.setGeometry(QtCore.QRect(4, 449, 38, 27))
        self.btn_twitter.setAutoFillBackground(True)
        self.btn_twitter.setText(_fromUtf8(""))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/twitter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_twitter.setIcon(icon15)
        self.btn_twitter.setIconSize(QtCore.QSize(16, 16))
        self.btn_twitter.setFlat(True)
        self.btn_twitter.setObjectName(_fromUtf8("btn_twitter"))
        self.ck_vlc = QtGui.QCheckBox(Form)
        self.ck_vlc.setGeometry(QtCore.QRect(440, 100, 58, 20))
        self.ck_vlc.setAutoFillBackground(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("imagenes/vlc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ck_vlc.setIcon(icon16)
        self.ck_vlc.setIconSize(QtCore.QSize(16, 16))
        self.ck_vlc.setObjectName(_fromUtf8("ck_vlc"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(2, 85, 35, 35))
        self.label_8.setBaseSize(QtCore.QSize(45, 45))
        self.label_8.setAutoFillBackground(True)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8("imagenes/python-3.png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lbl_barr = QtGui.QLabel(Form)
        self.lbl_barr.setGeometry(QtCore.QRect(70, 60, 351, 20))
        self.lbl_barr.setAutoFillBackground(True)
        self.lbl_barr.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_barr.setObjectName(_fromUtf8("lbl_barr"))
        self.p_bar = QtGui.QProgressBar(Form)
        self.p_bar.setGeometry(QtCore.QRect(40, 40, 451, 23))
        self.p_bar.setProperty("value", 0)
        self.p_bar.setObjectName(_fromUtf8("p_bar"))
        self.web = QtWebKit.QWebView(Form)
        self.web.setGeometry(QtCore.QRect(9, 150, 571, 261))
        self.web.setAutoFillBackground(True)
        self.web.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.web.setObjectName(_fromUtf8("web"))
        self.web.settings().setAttribute(QtWebKit.QWebSettings.PluginsEnabled, True)
        self.lbl_autor = QtGui.QLabel(Form)
        self.lbl_autor.setGeometry(QtCore.QRect(64, 417, 411, 16))
        self.lbl_autor.setAutoFillBackground(True)
        self.lbl_autor.setObjectName(_fromUtf8("lbl_autor"))
        self.btn_valida_2 = QtGui.QPushButton(Form)
        self.btn_valida_2.setGeometry(QtCore.QRect(470, 412, 101, 27))
        self.btn_valida_2.setAutoFillBackground(True)
        self.btn_valida_2.setIcon(icon6)
        self.btn_valida_2.setFlat(True)
        self.btn_valida_2.setObjectName(_fromUtf8("btn_valida_2"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(14, 416, 40, 16))
        self.label_2.setAutoFillBackground(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.btn_valida.setToolTip(_translate("Form", "Buscar Video", None))
        self.btn_valida.setText(_translate("Form", "...", None))
        self.label_7.setText(_translate("Form", "Ejemplo: http://www.youtube.com/watch?v=QJO3ROT-A4E ", None))
        self.lbl_desc.setToolTip(_translate("Form", "Introduce la URL de Youtube", None))
        self.lbl_desc.setText(_translate("Form", "TextLabel", None))
        self.btn_folder.setToolTip(_translate("Form", "Motrar Videos", None))
        self.btn_folder.setText(_translate("Form", ">", None))
        self.treeView.setToolTip(_translate("Form", "Directorio Videos", None))
        self.lbl_perfil.setText(_translate("Form", "TextLabel", None))
        self.btn_folder_2.setToolTip(_translate("Form", "<html><head/><body><p>Abrir Carpeta de Videos</p></body></html>", None))
        self.btn_folder_2.setText(_translate("Form", "...", None))
        self.lst_encola.setToolTip(_translate("Form", "Lista de Descarga", None))
        self.btn_add.setToolTip(_translate("Form", "Mostrar Lista", None))
        self.btn_add.setText(_translate("Form", ">", None))
        self.ck_captura.setToolTip(_translate("Form", "Capturar Enlaces de Youtube en Automatico", None))
        self.ck_captura.setText(_translate("Form", "Capturar Enlaces", None))
        self.ck_lst_auto.setToolTip(_translate("Form", "Lista Automatica", None))
        self.ck_lst_auto.setText(_translate("Form", "Lista Automatica", None))
        self.btn_add_video.setToolTip(_translate("Form", "Añadir Link a la Lista de Descargas", None))
        self.btn_add_video.setText(_translate("Form", "Añadir Video", None))
        self.btn_add_lista.setToolTip(_translate("Form", "Descargar Lista de videos", None))
        self.btn_add_lista.setText(_translate("Form", "Descargar Lista", None))
        self.btn_paypal.setToolTip(_translate("Form", "Donar en PayPal", None))
        self.label.setText(_translate("Form", "Formato:", None))
        self.f_box.setToolTip(_translate("Form", "Formato", None))
        self.f_box.setItemText(0, _translate("Form", "mp4", None))
        self.f_box.setItemText(1, _translate("Form", "mp3", None))
        self.f_box.setItemText(2, _translate("Form", "3gp", None))
        self.f_box.setItemText(3, _translate("Form", "webm", None))
        self.f_box.setItemText(4, _translate("Form", "flv", None))
        self.btn_de_item.setToolTip(_translate("Form", "Eliminar Link", None))
        self.btn_de_item.setText(_translate("Form", "Eliminar Link", None))
        self.btn_facebook.setToolTip(_translate("Form", "Sigueme en Facebook", None))
        self.btn_google.setToolTip(_translate("Form", "Sigueme en G+", None))
        self.btn_twitter.setToolTip(_translate("Form", "Sigueme en Twitter", None))
        self.ck_vlc.setToolTip(_translate("Form", "Reproducir Videos en VLC", None))
        self.ck_vlc.setText(_translate("Form", "vlc", None))
        self.label_8.setToolTip(_translate("Form", "<html><head/><body><p>Programado en Python! y PyQt4 ..  xskyofx@gmail.com</p></body></html>", None))
        self.lbl_barr.setText(_translate("Form", "-----", None))
        self.lbl_autor.setText(_translate("Form", "Autor:", None))
        self.btn_valida_2.setToolTip(_translate("Form", "Descarga el Video", None))
        self.btn_valida_2.setText(_translate("Form", "Descargar", None))
        self.label_2.setText(_translate("Form", "Autor:", None))

from PyQt4 import QtWebKit
from PyQt4.QtNetwork import *
from PyQt4.QtWebKit import QWebView,QWebPage